In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense,Dropout
from google.colab import files

In [ ]:
files.upload()

In [ ]:
  spam = pd.read_csv('spam.csv',encoding='latin-1')
  spam.head()

In [4]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(spam['Category'])
print(y)

[0 0 1 ... 0 0 0]


In [ ]:
# divide os dados
menssagem = spam['Message'].values
X_train, X_test, y_trainm, y_test = train_test_split(menssagem, y, test_size=0.3)

print(X_train)

In [6]:
vetorizador = CountVectorizer()
vetorizador.fit(X_train)
X_train = vetorizador.transform(X_train)
X_test = vetorizador.transform(X_test)

print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [ ]:
X_train.toarray()[0]

In [9]:
print(X_train.shape[1])

7300


In [ ]:
modelo = Sequential()

modelo.add(Dense(units = 10, activation = 'relu', input_dim = X_train.shape[1]))
modelo.add(Dropout(0.1))
modelo.add(Dense(units = 8, activation = 'relu'))
modelo.add(Dropout(0.1))
modelo.add(Dense(units = 1, activation = 'sigmoid'))


In [11]:
modelo.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])
modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │          73,010 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 10)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 8)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 73,107 (285.57 KB)

 Trainable params: 73,107 (285.57 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
modelo.fit(X_train, y_trainm, epochs = 20, batch_size = 10, verbose = True, validation_data = (X_test, y_test))

In [13]:
loss, accuracy = modelo.evaluate(X_test, y_test)
print('Loss: ', loss)
print('Accuracy: ', accuracy)

53/53 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9787 - loss: 0.0173
Loss:  0.015039799734950066
Accuracy:  0.9814593195915222


In [ ]:
nova_previsao = modelo.predict(X_test)
print(nova_previsao)

In [ ]:
prev = (nova_previsao > 0.5)
print(prev)

In [17]:
cm = confusion_matrix(y_test, prev)
print(cm)

[[1448    7]
 [  24  193]]
